version: '2'
services:
   front:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "3000:8000"
      volumes:
         - /app/node_modules
         - .:/app
      command: ["npm","run","dev"]